
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action FileAction;
	
	private global::Gtk.Action ExitAction;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.MenuBar menubar1;
	
	private global::Gtk.Notebook nbTabs;
	
	private global::Gtk.VBox vbox2;
	
	private global::Gtk.HBox hbox2;
	
	private global::Gtk.Label label3;
	
	private global::Gtk.ComboBox cbTubes;
	
	private global::Gtk.Button button1;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TreeView statisticsTree;
	
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.Button button2;
	
	private global::Gtk.Label label1;
	
	private global::Gtk.HBox hbox3;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	
	private global::Gtk.TreeView servicesTree;
	
	private global::Gtk.VBox vbox3;
	
	private global::Gtk.Button button3;
	
	private global::Gtk.Button button4;
	
	private global::Gtk.Label label2;
	
	private global::Gtk.HBox hbox4;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow2;
	
	private global::Gtk.TreeView thirdPartiesTree;
	
	private global::Gtk.VBox vbox4;
	
	private global::Gtk.Button button13;
	
	private global::Gtk.Button button14;
	
	private global::Gtk.Label label4;
	
	private global::Gtk.Statusbar statusbar1;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.ExitAction = new global::Gtk.Action ("ExitAction", global::Mono.Unix.Catalog.GetString ("Exit"), null, null);
		this.ExitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Exit");
		w1.Add (this.ExitAction, "<Primary>q");
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menuitem name='ExitAction' action='ExitAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.nbTabs = new global::Gtk.Notebook ();
		this.nbTabs.CanFocus = true;
		this.nbTabs.Name = "nbTabs";
		this.nbTabs.CurrentPage = 1;
		// Container child nbTabs.Gtk.Notebook+NotebookChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		this.hbox2.BorderWidth = ((uint)(6));
		// Container child hbox2.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Tubes");
		this.hbox2.Add (this.label3);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label3]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.cbTubes = global::Gtk.ComboBox.NewText ();
		this.cbTubes.Name = "cbTubes";
		this.hbox2.Add (this.cbTubes);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.cbTubes]));
		w4.Position = 1;
		// Container child hbox2.Gtk.Box+BoxChild
		this.button1 = new global::Gtk.Button ();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseStock = true;
		this.button1.UseUnderline = true;
		this.button1.Label = "gtk-refresh";
		this.hbox2.Add (this.button1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.button1]));
		w5.PackType = ((global::Gtk.PackType)(1));
		w5.Position = 2;
		w5.Expand = false;
		w5.Fill = false;
		this.vbox2.Add (this.hbox2);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.statisticsTree = new global::Gtk.TreeView ();
		this.statisticsTree.CanFocus = true;
		this.statisticsTree.Name = "statisticsTree";
		this.GtkScrolledWindow.Add (this.statisticsTree);
		this.vbox2.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.GtkScrolledWindow]));
		w8.Position = 1;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.button2 = new global::Gtk.Button ();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseStock = true;
		this.button2.UseUnderline = true;
		this.button2.Label = "gtk-execute";
		this.hbox1.Add (this.button2);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button2]));
		w9.Position = 2;
		w9.Expand = false;
		w9.Fill = false;
		this.vbox2.Add (this.hbox1);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
		w10.Position = 2;
		w10.Expand = false;
		w10.Fill = false;
		this.nbTabs.Add (this.vbox2);
		// Notebook tab
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Beanstalk");
		this.nbTabs.SetTabLabel (this.vbox2, this.label1);
		this.label1.ShowAll ();
		// Container child nbTabs.Gtk.Notebook+NotebookChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.servicesTree = new global::Gtk.TreeView ();
		this.servicesTree.CanFocus = true;
		this.servicesTree.Name = "servicesTree";
		this.GtkScrolledWindow1.Add (this.servicesTree);
		this.hbox3.Add (this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.GtkScrolledWindow1]));
		w13.Position = 0;
		// Container child hbox3.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		this.vbox3.BorderWidth = ((uint)(6));
		// Container child vbox3.Gtk.Box+BoxChild
		this.button3 = new global::Gtk.Button ();
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseStock = true;
		this.button3.UseUnderline = true;
		this.button3.Label = "gtk-new";
		this.vbox3.Add (this.button3);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.button3]));
		w14.Position = 0;
		w14.Expand = false;
		w14.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.button4 = new global::Gtk.Button ();
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseStock = true;
		this.button4.UseUnderline = true;
		this.button4.Label = "gtk-edit";
		this.vbox3.Add (this.button4);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.button4]));
		w15.Position = 1;
		w15.Expand = false;
		w15.Fill = false;
		this.hbox3.Add (this.vbox3);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vbox3]));
		w16.Position = 2;
		w16.Expand = false;
		w16.Fill = false;
		this.nbTabs.Add (this.hbox3);
		global::Gtk.Notebook.NotebookChild w17 = ((global::Gtk.Notebook.NotebookChild)(this.nbTabs [this.hbox3]));
		w17.Position = 1;
		// Notebook tab
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Services");
		this.nbTabs.SetTabLabel (this.hbox3, this.label2);
		this.label2.ShowAll ();
		// Container child nbTabs.Gtk.Notebook+NotebookChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
		this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
		this.thirdPartiesTree = new global::Gtk.TreeView ();
		this.thirdPartiesTree.CanFocus = true;
		this.thirdPartiesTree.Name = "thirdPartiesTree";
		this.GtkScrolledWindow2.Add (this.thirdPartiesTree);
		this.hbox4.Add (this.GtkScrolledWindow2);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.GtkScrolledWindow2]));
		w19.Position = 0;
		// Container child hbox4.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		this.vbox4.BorderWidth = ((uint)(6));
		// Container child vbox4.Gtk.Box+BoxChild
		this.button13 = new global::Gtk.Button ();
		this.button13.CanFocus = true;
		this.button13.Name = "button13";
		this.button13.UseStock = true;
		this.button13.UseUnderline = true;
		this.button13.Label = "gtk-new";
		this.vbox4.Add (this.button13);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.button13]));
		w20.Position = 0;
		w20.Expand = false;
		w20.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.button14 = new global::Gtk.Button ();
		this.button14.CanFocus = true;
		this.button14.Name = "button14";
		this.button14.UseStock = true;
		this.button14.UseUnderline = true;
		this.button14.Label = "gtk-edit";
		this.vbox4.Add (this.button14);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.button14]));
		w21.Position = 1;
		w21.Expand = false;
		w21.Fill = false;
		this.hbox4.Add (this.vbox4);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox4]));
		w22.Position = 2;
		w22.Expand = false;
		w22.Fill = false;
		this.nbTabs.Add (this.hbox4);
		global::Gtk.Notebook.NotebookChild w23 = ((global::Gtk.Notebook.NotebookChild)(this.nbTabs [this.hbox4]));
		w23.Position = 2;
		// Notebook tab
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Third Parties");
		this.nbTabs.SetTabLabel (this.hbox4, this.label4);
		this.label4.ShowAll ();
		this.vbox1.Add (this.nbTabs);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.nbTabs]));
		w24.Position = 1;
		// Container child vbox1.Gtk.Box+BoxChild
		this.statusbar1 = new global::Gtk.Statusbar ();
		this.statusbar1.Name = "statusbar1";
		this.statusbar1.Spacing = 6;
		this.vbox1.Add (this.statusbar1);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.statusbar1]));
		w25.Position = 2;
		w25.Expand = false;
		w25.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.ExitAction.Activated += new global::System.EventHandler (this.OnExit);
		this.nbTabs.SwitchPage += new global::Gtk.SwitchPageHandler (this.OnSwitchPage);
		this.button1.Clicked += new global::System.EventHandler (this.OnRefreshTubes);
		this.button2.Clicked += new global::System.EventHandler (this.OnGetStatistics);
		this.servicesTree.RowActivated += new global::Gtk.RowActivatedHandler (this.OnServiceActivated);
		this.button3.Clicked += new global::System.EventHandler (this.OnNewService);
		this.button4.Clicked += new global::System.EventHandler (this.OnEditService);
		this.button13.Clicked += new global::System.EventHandler (this.OnNewThirdParty);
		this.button14.Clicked += new global::System.EventHandler (this.OnEditThirdParty);
	}
}
